spring:
  application:
    name: alert-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: "10"
      connection-timeout: "30000"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: ${PORT}
logging:
  level:
    root: INFO
    org:
      hibernate: DEBUG
      springframework: DEBUG
service:
  patient:
    url: ${PATIENT_SERVICE_URL}
